version: '3.3'
# For local development only
services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
    - db
    image: wordpress:php7.2
    ports:
    - "8000:80"
    volumes:
    - /var/www/html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

#  phpmyadmin:
#    depends_on:
#    - db
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#    - "8080:80"
#    environment:
#      PMA_HOST: db
#      PMA_PORT: "3306:3306"
#      MYSQL_ROOT_PASSWORD: somewordpress
volumes:
  db_data: